
package es.rchavarria.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsersManagement", targetNamespace = "http://ws.rchavarria.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsersManagement {


    /**
     * 
     * @param name
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://ws.rchavarria.es/", className = "es.rchavarria.ws.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://ws.rchavarria.es/", className = "es.rchavarria.ws.AddUserResponse")
    public int addUser(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.rchavarria.es/", className = "es.rchavarria.ws.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.rchavarria.es/", className = "es.rchavarria.ws.GetUserResponse")
    public String getUser(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

}
