
package es.rchavarria.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UsersManagementService", targetNamespace = "http://ws.rchavarria.es/", wsdlLocation = "http://localhost:8080/Users?wsdl")
public class UsersManagementService
    extends Service
{

    private final static URL USERSMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERSMANAGEMENTSERVICE_EXCEPTION;
    private final static QName USERSMANAGEMENTSERVICE_QNAME = new QName("http://ws.rchavarria.es/", "UsersManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Users?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSMANAGEMENTSERVICE_WSDL_LOCATION = url;
        USERSMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public UsersManagementService() {
        super(__getWsdlLocation(), USERSMANAGEMENTSERVICE_QNAME);
    }

    public UsersManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSMANAGEMENTSERVICE_QNAME, features);
    }

    public UsersManagementService(URL wsdlLocation) {
        super(wsdlLocation, USERSMANAGEMENTSERVICE_QNAME);
    }

    public UsersManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSMANAGEMENTSERVICE_QNAME, features);
    }

    public UsersManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsersManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsersManagement
     */
    @WebEndpoint(name = "UsersManagementPort")
    public UsersManagement getUsersManagementPort() {
        return super.getPort(new QName("http://ws.rchavarria.es/", "UsersManagementPort"), UsersManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsersManagement
     */
    @WebEndpoint(name = "UsersManagementPort")
    public UsersManagement getUsersManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.rchavarria.es/", "UsersManagementPort"), UsersManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw USERSMANAGEMENTSERVICE_EXCEPTION;
        }
        return USERSMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
